name: Generate 3D Contribution Graph

on:
  schedule: # Runs automatically every 24 hours
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows manual run

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D Contrib Graph
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push 3D Graph to repo
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated 3D contribution graph"
          git push
